;
; File generated by cc65 v 2.19 - Git 4e0806c6b
;
	.fopt		compiler,"cc65 v 2.19 - Git 4e0806c6b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax ;a 
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$05
	ldx     #$00
	jsr     pusheax ;x
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax ;push x to stack
	ldy     #$0B
	jsr     ldeaxysp ;load a
	jsr     tosgteax
	jeq     L0002
	ldy     #$03
	jsr     ldeaxysp
	ldy     #$04
	jsr     steaxysp
	jmp     L0003
L0002:	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	ldy     #$04
	jsr     steaxysp
L0003:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

