;
; File generated by cc65 v 2.19 - Git 29f7ab380
;
	.fopt		compiler,"cc65 v 2.19 - Git 29f7ab380"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	jsr     pushax
	ldy     #$01
	jsr     ldaxysp
	cpx     #$00
	bne     L0003
	cmp     #$00
L0003:	jsr     booleq
	jeq     L0002
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staxysp
	jmp     L0004
L0002:	ldx     #$00
	lda     #$02
	ldy     #$00
	jsr     staxysp
L0004:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

