;
; File generated by cc65 v 2.19 - Git 4e0806c6b
;
	.fopt		compiler,"cc65 v 2.19 - Git 4e0806c6b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$0E
	jsr     subysp
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staxysp
L0002:	ldy     #$01
	jsr     ldaxysp
	cmp     #$03
	txa
	sbc     #$00
	bvc     L0006
	eor     #$80
L0006:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0005
	jmp     L0003
L0005:	ldy     #$01
	jsr     ldaxysp
	jsr     aslax2
	jsr     incax2
	jsr     leaaxsp
	ldy     #$03
	jsr     ldeaxidx
	ldy     #$02
	jsr     laddeqysp
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0003:	ldx     #$00
	lda     #$01
	jmp     L0001
L0001:	rts

.endproc

