;
; File generated by cc65 v 2.19 - Git 29f7ab380
;
	.fopt		compiler,"cc65 v 2.19 - Git 29f7ab380"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_fgetc
	.import		_fopen
	.import		_printf
	.export		_main

.segment	"RODATA"

S0003:
	.byte	$D2,$45,$41,$44,$49,$4E,$47,$20,$46,$49,$4C,$45,$20,$0D,$00
S0001:
	.byte	$54,$45,$58,$54,$2E,$54,$58,$54,$00
S0004:
	.byte	$25,$43,$00
S0002:
	.byte	$52,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _fopen
	ldy     #$02
	jsr     staxysp
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jmp     L0006
L0002:	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$04
L0006:	jsr     _printf
	ldy     #$03
	jsr     ldaxysp
	jsr     _fgetc
	jsr     stax0sp
	cpx     #$FF
	bne     L0002
	cmp     #$FF
	bne     L0002
	inx
	txa
	rts

.endproc

