;
; File generated by cc65 v 2.19 - Git 29f7ab380
;
	.fopt		compiler,"cc65 v 2.19 - Git 29f7ab380"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_fclose
	.import		_fgetc
	.import		_fopen
	.import		_printf
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$54,$54,$54,$2E,$54,$58,$54,$00
S0003:
	.byte	$25,$43,$00
S0002:
	.byte	$52,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _fopen
	ldy     #$02
	jsr     staxysp
	jmp     L0004
L0002:	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	jsr     _printf
L0004:	ldy     #$03
	jsr     ldaxysp
	jsr     _fgetc
	ldy     #$00
	jsr     staxysp
	cpx     #$FF
	bne     L0005
	cmp     #$FF
L0005:	jsr     boolne
	jne     L0002
	ldy     #$03
	jsr     ldaxysp
	jsr     _fclose
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

